# Challenge 1: Write a program that adds 3 numbers.
add add
++

# Challenge 2: Write a program that divides the first number by the second.
backward div
˜÷

# Challenge 3: Write a program that subtracts the second number from the first then
#              squares the result.
self mul backward sub
˙× ˜-

# Challenge 4: Write a program that adds the first number to the square root of the
#              second.
add dip sqrt
+⊙√
