# https://www.uiua.org/tutorial/More%20Array%20Manipulation

# Challenge 1: Write a program that adds the first argument list to each row of the
#              second argument matrix.
rows rows add fix
≡≡+¤
# ...or...
rows,`2 add fix
≡₋₂+¤
# ...or...
rows,<rows add
≡⌞≡+

# Challenge 2: Write a program that joins the first argument to each list in the second
#              argument.
rows,1join
≡₁⊂
